//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/// Generated from: lobby.proto
// <reference path="lobby_room.ts" />

module Cmd {
	/**
	 * ---------------------------------游戏设置相关----------------------------//
	 *  设置类型
	 */
	export enum SetType {
		/**
		 * 音乐
		 */
		Music = 1,
		/**
		 * 音效
		 */
		Sound = 2,
		/**
		 * 排行榜(淘金类型的金币排行榜)
		 */
		Rank = 3
	}
	/**
	 * ---------------------------------免费金币界面任务系统相关----------------------------//
	 */
	export enum TaskStatus {
		/**
		 * 任务未开始
		 */
		Task_Status_Unstart = 0,
		/**
		 * 任务进行中
		 */
		Task_Status_Progress = 1,
		/**
		 * 已完成
		 */
		Task_Status_Complete = 2,
		/**
		 * 已领取奖励
		 */
		Task_Status_Received = 3
	}
	/**
	 * ****好友相关****
	 */
	export enum MsgType {
		/**
		 * 底部菜单-&gt;商城
		 */
		Shop = 1,
		/**
		 * 底部菜单-&gt;好友
		 */
		Friend = 2,
		/**
		 * 底部菜单-&gt;救济金
		 */
		Alms = 3,
		/**
		 * 底部菜单-&gt;活动
		 */
		Activity = 4,
		/**
		 * 底部菜单-&gt;任务
		 */
		DaysTask = 5,
		/**
		 * 底部菜单-&gt;更多
		 */
		More = 6,
		/**
		 * 底部菜单-&gt;摇钱树
		 */
		MoneyTree = 7,
		/**
		 * 底部菜单-&gt;商城-&gt;礼品屋
		 */
		GiftHouse = 100,
		/**
		 * 底部菜单-&gt;好友-&gt;好友消息
		 */
		FriendMsg = 200,
		/**
		 * 底部菜单-&gt;好友-&gt;好友请求
		 */
		FriendReq = 201,
		/**
		 * 底部菜单-&gt;救济金-&gt;领取救济金
		 */
		GetAlms = 300,
		/**
		 * 底部菜单-&gt;活动-&gt;每日签到
		 */
		Act_DaySign = 400,
		/**
		 * 底部菜单-&gt;活动-&gt;幸运翻翻翻
		 */
		Act_TurnCard = 401,
		/**
		 * 底部菜单-&gt;活动-&gt;幸运大转盘
		 */
		Act_TurnTable = 402,
		/**
		 * 底部菜单-&gt;任务-&gt;挑战任务
		 */
		Task_fight = 500,
		/**
		 * 底部菜单-&gt;任务-&gt;充值任务
		 */
		Task_TurnTable = 501,
		/**
		 * 底部菜单-&gt;任务-&gt;每日任务
		 */
		Task_EveryDay = 502,
		/**
		 * 底部菜单-&gt;任务-&gt;成就任务
		 */
		Task_Once = 503,
		/**
		 * 底部菜单-&gt;更多-&gt;公告
		 */
		Task_Notice = 600,
		/**
		 * 底部菜单-&gt;更多-&gt;魅力值
		 */
		Task_Charm = 601,
		/**
		 * 底部菜单-&gt;更多-&gt;邮件
		 */
		Task_NewMail = 602,
		/**
		 * 底部菜单-&gt;更多-&gt;vip
		 */
		Task_VIP = 603,
		/**
		 * 底部菜单-&gt;摇钱树-&gt;领取金币
		 */
		Task_MoneyTree = 701
	}
	/**
	 * 用户信息获取
	 */
	export class UserInfoGetLbyCmd_C {
		/**
		 * 用户ID,当为空时，说明是自己的信息
		 */
		uid: number;
		GetType(): string { return 'Cmd.UserInfoGetLbyCmd_C'; }
	}
		/**
	 * 用户信息获取
	 */
	export class UserInfoSynLobbyCmd_S {
		/**
		 * 用户ID,当为空时，说明是自己的信息
		 */
		uid: number;
		GetType(): string { return 'Cmd.UserInfoGetLbyCmd_C'; }
	}
	export class UserInfoGetLbyCmd_S {
		/**
		 * 返回码
		 */
		resultCode: number;
		/**
		 * 仅当不存在时，返回错误描述
		 */
		desc: string;
	
		GetType(): string { return 'Cmd.UserInfoGetLbyCmd_S'; }
	}
	/**
	 * 房间数据 用于请求信息同步时 检测玩家是否已经在某个房间中
	 */
	export class UserRoomInfo {
		/**
		 * 返回当前创建的房间号 所对应的游戏id
		 */
		gameId: number;
		/**
		 * 返回当前创建的房间号 所对应的游戏区id
		 */
		zoneId: number;
		/**
		 * 房间号
		 */
		roomId: number;
s	
		/**
		 * 场景 为匹配场则传
		 */
		scene: number;
		/**
		 * 该房间创建时为几人房 -- 牛牛人数不同ui不一致
		 */
		baseUserNbr: number;
		GetType(): string { return 'Cmd.UserRoomInfo'; }
	}
	
	/**
	 * 积分商城物品列表
	 */
	export class ShopPointItem {
		/**
		 * 物品ID
		 */
		goodId: number;
		/**
		 * 物品数量
		 */
		goodNbr: number;
		/**
		 * 商品名称
		 */
		goodName: string;
		/**
		 * 需要积分
		 */
		needPoint: number;
		GetType(): string { return 'Cmd.ShopPointItem'; }
	}
	
}
