//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module weChat {
	/**
	 * FILE: 创建房间选项.xlsx SHEET: 
	 */
	export class TableCoinHundredConfig {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 游戏ID
		 */
		gameId: number;
		/**
		 * 游戏名称
		 */
		GameName: string;
		/**
		 * 房间序号
		 */
		roomType: number;
		/**
		 * 房间名称
		 */
		roomName: string;
		/**
		 * 金币底注
		 */
		lowestBetChips: number;
		/**
		 * 最低携带
		 */
		lowestCarry: number;
		/**
		 * 最高携带
		 */
		highestCarry: number;
		/**
		 * 金币场抽水
		 */
		coinGameCost: number;
		/**
		 * 人数
		 */
		userNum: number;
		/**
		 * 机器人最低携带
		 */
		robotLowestCarry: number;
		/**
		 * 机器人最高携带
		 */
		robotHighestCarry: number;
		/**
		 * 图片名
		 */
		imageName: string;

		GetType(): string { return 'table.TableCoinHundredConfig'; }
	}
}
